# Generated by Django 2.0.2 on 2018-05-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecast_data',
            options={'verbose_name_plural': 'Forecast Data'},
        ),
        migrations.AlterField(
            model_name='forecast_data',
            name='dvo_data',
            field=models.IntegerField(default=0, verbose_name='Palay Volume (Metric Tons)'),
        ),
        migrations.AlterField(
            model_name='forecast_data',
            name='humidity',
            field=models.FloatField(default=0, verbose_name='Humidity AVG (%)'),
        ),
        migrations.AlterField(
            model_name='forecast_data',
            name='quarter',
            field=models.IntegerField(choices=[(1, 'Quarter 1'), (2, 'Quarter 2'), (3, 'Quarter 3'), (4, 'Quarter 4')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='forecast_data',
            name='rainfall',
            field=models.FloatField(default=0, verbose_name='Rainfall AVG (mm)'),
        ),
        migrations.AlterField(
            model_name='forecast_data',
            name='sunshine',
            field=models.FloatField(default=0, verbose_name='Visibility AVG (km)'),
        ),
        migrations.AlterField(
            model_name='forecast_data',
            name='temperature',
            field=models.FloatField(default=0, verbose_name='Temperature AVG (°C)'),
        ),
    ]
