# Generated by Django 2.0.2 on 2018-05-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0003_auto_20180527_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast_data',
            name='humidity',
            field=models.FloatField(default=0, verbose_name='Visibility AVG (km)'),
        ),
        migrations.AlterField(
            model_name='forecast_data',
            name='sunshine',
            field=models.FloatField(default=0, verbose_name='Humidity AVG (%)'),
        ),
    ]
