# Generated by Django 2.0.2 on 2018-06-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0005_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='prediction',
            field=models.FloatField(default=0, verbose_name='Palay Volume (Metric Tons)'),
        ),
    ]
